"""first

Revision ID: 45227edbe3bd
Revises: 
Create Date: 2023-07-04 19:51:53.066741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45227edbe3bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_index(op.f('ix_cars_car_id'), 'cars', ['car_id'], unique=True)
    op.create_table('service',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_index(op.f('ix_service_s_id'), 'service', ['s_id'], unique=True)
    op.create_table('clients',
    sa.Column('cl_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car'], ['cars.car_id'], ),
    sa.PrimaryKeyConstraint('cl_id')
    )
    op.create_index(op.f('ix_clients_cl_id'), 'clients', ['cl_id'], unique=True)
    op.create_table('service_orders',
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('car_client', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Boolean(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_client'], ['clients.cl_id'], ),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_index(op.f('ix_service_orders_so_id'), 'service_orders', ['so_id'], unique=True)
    op.create_table('service_orders_service',
    sa.Column('service_order_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.s_id'], ),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.so_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_orders_service')
    op.drop_index(op.f('ix_service_orders_so_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_clients_cl_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_service_s_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_cars_car_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
